version: 1.0.{build}
os: Windows Server 2012

install:
  - echo This is batch

build:
  project: MonoXunit.sln

test_script:
  - packages\xunit.runners.1.9.2\tools\xunit.console.clr4.x86.exe bin\Debug\MonoXunit.Tests.dll
